name=Breath
version=1.0.0
author=Holman Buenaventura
maintainer=Holman Buenaventura
sentence=Ultra-fast breath sensor library for electronic wind instruments (EWI).
paragraph=Optimized for wind controllers. Read and scale air pressure sensors with zero runtime division overhead.
category=Sensors
url=https://github.com/habuenav/Breath
architectures=*
depends=quickMap
